### PR TITLE
EatIT

### PR DESCRIPTION
**Pull request by Xiaoming94**
Designade om EatIT lite granna.

Kanske går att göra något mer, tänkte lite på animeringar.

### CODE REVIEW

**Comment by oskar367** [comment]
I love it! It does feel like it the order "cards" are a bit too big. If we had this last tuesday I would have to scroll alot while ordering

**Comment by Hultner** [comment]
Maybe attach a screenshot so that the suggested new design can be previewed
easily.

onsdag 20 januari 2016 skrev Henry Yang <notifications@github.com>:

**Comment by oskar367** [comment]
https://i.imgur.com/km2L7Ge.png

**Comment by Xiaoming94** [comment]
Hi! Maybe changing the fontsizes will make the "cards" smaller. You want me to make the change?

**Comment by Xiaoming94** [comment]
How about now? :)

**Comment by Hultner** [comment]
First for future reference please attach the screenshot directly to the issue instead of using an external hosting service as I've done below. 
screenshot_2016-01-21_13-41-05

And some minor suggestions for further improvement while you're at it
* The boxes convey a unbalanced state of mind, the left (and likewise right) padding should be the same as the space above and under the text. 
* Maybe have one larger box with every item separated by a thin border instead of several small. Current implementation gives an crowded and cluttered impression.
* EatIT header would probably look better in white.
* The text and link at the top looks misplaced as it's in the background on a level below the orders and header
* Same is true for the input area at the bottom, on top of that they give a very malplaced impression and should probably med modified to follow the same design standard as the rest of the application thus giving a more unified aesthetic appearance.

**Comment by Xiaoming94** [comment]
Hello digIT, thanks for the response, I'm currently working on some improvements and I shall do my best so that by tomorrow we wouldn't have to endure another aspning with the old design of EatIT

Regarding to what Hultner Wrote:
* Ugh... You are correct, shall change it immediatly
* That was actually my first Idea but, than I couldn't find a way to make it look nice since than the box will be very small at stat and it felt like meeeh... (If you know what I mean), Than I came up with this "Card"-design. 
* Are you referring about the background or foreground(font) color?
* I have actually been thinking about placing the link in the header, maybe that will work? Otherwise, I don't really mind the text being in a lower level than the header and the orders, maybe it's just personal taste. The overall design is kind of inspired by Google's material design, Some of their services does this too
* Yeap... You are right... They still look awful and now, also, out of place... Working on it.

**Comment by Xiaoming94** [comment]
O well, now I'm done.

**Comment by Hultner** [comment]
Please add a screenshot so that the updates can be easily reviewed without checking out your repository.

**Comment by Xiaoming94** [comment]
2016-01-25-16 13 39-screenshot

**Pull request merged**
