### PR TITLE
ReactJS 

### PR DESCRIPTION
**Pull request by Portals**

### CODE REVIEW

**Comment by Portals** [comment]
I cannot run prod.docker-compose..yml. I get the follwoing error: 

```

**Comment by Portals** [comment]
Also, when trying to start docker-compose.yml I get this error:

```
Starting eatit_eatit_1 ... done
Attaching to eatit_eatit_1
eatit_1  | npm ERR! code ENOGIT
eatit_1  | npm ERR! No git binary found in $PATH
eatit_1  | npm ERR! 
eatit_1  | npm ERR! Failed using git.
eatit_1  | npm ERR! Please check if you have git installed and in your PATH.
eatit_1  | 
eatit_1  | npm ERR! A complete log of this run can be found in:
eatit_1  | npm ERR!     /home/meteor/.npm/_logs/2018-07-26T09_51_38_949Z-debug.log
eatit_eatit_1 exited with code 1
```

**Comment by lindskogen** [comment]
@Portals how about now?

**Comment by Portals** [comment]
It resolved the problem with the develop docker-compose file, but the same error still persist for the production one.

**Comment by Portals** [comment]
Production docker now works. Great work @lindskogen! Thanks for rewriting into a sensible frontend framwork! :rocket:

**Pull request merged**
