### PR TITLE
Add link to swish app

### PR DESCRIPTION
**Pull request by lindskogen**
Maybe needs better UX design :)

image

### CODE REVIEW

**Comment by Dr-Horv** [comment]
:D

**Comment by Xiaoming94** [comment]
@lindskogen Does it? If it already does what it does, I don't see any necessities :)

**Comment by jesperlindstrom** [comment]
@lindskogen did you try this on a real device? I'm getting this when I try it on eatit.chalmers.it:
img_1315

Not sure if I'm missing something.

**Comment by lindskogen** [comment]
You cannot swish yourself

**Comment by jesperlindstrom** [comment]
Actually doesn't help if I enter someone else's number. I removed spaces and dashes from the phone number and made sure to place an order before. But it works for you?

**Pull request merged**
